dist:
  # https://docs.travis-ci.com/user/reference/bionic/
  - bionic
language:
  - node_js
node_js:
  - "12"
  - "14"
install:
  - npm install
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
